# Generated by Django 5.0.6 on 2024-09-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menany', '0002_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
